export type player_death = {
	assistedflash: boolean;
	assister_is_warmup_period: boolean;
	assister_name: string;
	assister_steamid: string;
	assister_team_clan_name: string;
	assister_team_name: string;
	assister_team_rounds_total: number;
	attacker_is_warmup_period: boolean;
	attacker_name: string;
	attacker_steamid: string;
	attacker_team_clan_name: string;
	attacker_team_name: string;
	attacker_team_rounds_total: number;
	attackerblind: boolean;
	ct_team_clan_name: string;
	ct_team_name: string;
	ct_team_rounds_total: number;
	distance: number;
	dmg_armor: number;
	dmg_health: number;
	dominated: number;
	event_name: string;
	headshot: boolean;
	hitgroup: number;
	is_warmup_period: boolean;
	noreplay: boolean;
	noscope: boolean;
	penetrated: number;
	revenge: number;
	round_win_status: number;
	t_team_clan_name: string;
	t_team_name: string;
	t_team_rounds_total: number;
	thrusmoke: boolean;
	tick: number;
	total_rounds_played: number;
	user_is_warmup_period: boolean;
	user_name: string;
	user_steamid: string;
	user_team_clan_name: string;
	user_team_name: string;
	user_team_rounds_total: number;
	weapon: string;
	weapon_fauxitemid: string;
	weapon_itemid: string;
	weapon_originalowner_xuid: string;
	wipe: number;
};

export type header = {
	addons: string;
	allow_clientside_entities: string;
	allow_clientside_particles: string;
	client_name: string;
	demo_file_stamp: string;
	demo_version_guid: string;
	demo_version_name: string;
	fullpackets_version: string;
	game_directory: string;
	map_name: string;
	network_protocol: string;
	server_name: string;
};

export type playerinfo = {
	name: string;
	steamid: string;
	team_number: number;
};
